services:
  - type: web
    name: checkin
    env: python
    startCommand: gunicorn checkin_jump.checkin_jump.wsgi:application
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
