# Generated by Django 5.1.7 on 2025-04-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0005_pequenogrupo_alter_adolescente_pg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescente',
            name='pg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PequenoGrupo',
        ),
    ]
