# Generated by Django 5.1.7 on 2025-04-25 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0006_alter_adolescente_pg_delete_pequenogrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PequenoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adolescente',
            name='pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adolescentes', to='adolescentes.pequenogrupo'),
        ),
    ]
